### ISSUE TITLE
Should we have an options object that allows precedence for command-line arguments?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/env2#1]
Should we allow command-line arguments or system/deployment environment variables to take precedence over values defined in `env.json` or vice-versa?

**Comment by nelsonic** [comment]
Closing as we are keeping `env2` as simple as possible for now.
Please re-open this issue if you feel strongly about this feature...

**Comment by cameronroe** [comment]
I think you should. That's what the original env did and https://github.com/kentcdodds/cross-env does.

**Comment by nelsonic** [comment]
@cameronroe well done for _digging out_ this issue! 😉 
I think https://github.com/kentcdodds/cross-env has a _slightly_ different goal than `env2` in that `cross-env` is attempting to make environment variables behave consistently across platforms whereas we are only trying to variables defined in a _file_ into the `process.env` object.
but you have _reminded_ us that `env2` does not have _explicit_ support for Windows ...

**Comment by cameronroe** [comment]
Yep, and how would env2 run on the server? With a command, it can be easily put into a CI build to run the service.

**Comment by nelsonic** [comment]
@cameronroe `env2` does not have a "CLI" or "bin script". 
it's used _exclusively_ in `.js` file to load an `.env` file which contains the list of environment variables. 
On our CI service or Heroku we do not load and `.env` file we define the required environment variables using the interface. 
e.g: https://github.com/dwyl/learn-environment-variables#using-environment-variables-with-travis-ci-
