### ISSUE TITLE
Confusing: not actually 12 factor app config approach

### ISSUE THREAD

**Issue by timruffles** [dwyl/env2#11]
`env2` looks like a nice way to manage config, it's just not the [12fa](http://12factor.net/config) way to manage config. As it currently stands, `env2` doesn't actually allow you to take in config from the environment! :)

Unless I'm missing something, 12fa explicitly calls out the pattern in `env2` as an [anti-pattern](http://12factor.net/config), and provides good reasons to avoid it:

> Another approach to config is the use of config files which are not checked into revision control, such as config/database.yml in Rails. This is a huge improvement over using constants which are checked into the code repo, but still has weaknesses: it’s easy to mistakenly check in a config file to the repo; there is a tendency for config files to be scattered about in different places and different formats, making it hard to see and manage all the config in one place. Further, these formats tend to be language- or framework-specific.

> Env vars are easy to change between deploys without changing any code; unlike config files, there is little chance of them being checked into the code repo accidentally; and unlike custom config files, or other config mechanisms such as Java System Properties, they are a language- and OS-agnostic standard.

**Comment by nelsonic** [comment]
@timruffles how do *you* solve this problem? (*we really want to know the right way of solving this!*)

**Comment by nelsonic** [comment]
Also, we *specifically* do not *over-write* any environment variables if they were set in the environment
see: https://github.com/dwyl/env2/blob/b431b97c5d85e160b70132e415f4f261eb326889/lib/env.js#L32-L34

**Comment by timruffles** [comment]
Last time I stored all app config in ansible (~ whichever deploy/automation tool you use), and then built the environment for each app programatically when the infrastructure was created. I ended up with a `service.sh` file run by a process manager (`runit`, `systemd`, `pm2` etc) which set the environment and the booted the app:

```sh
#!/bin/bash

export DB=postgres://someone:somepass@something.com/database
export FOO=bar

exec node my-app.js
```

Inside the app I normally loaded in the config via [`getenv`](https://www.npmjs.com/package/getenv) with defaults for simple development[1], the defaults being disabled in production via `env.disableFallbacks()`.

[1]: e.g `var REDIS_URL = getenv("DB", "tcp://localhost:6379");`

**Comment by timruffles** [comment]
Also, like I said, the 'config in repo and in .gitignore' is a fine way to do config: it works, it's simple. I think it's actually better for smaller projects/teams that don't deploy to 10-100s of servers, as 12fa config requires additional faff. The 12fa way is designed for large cloud deployments, immutable infrastructure etc - it's not the *right* way for any and all projects.

**Comment by nelsonic** [comment]
Right, but I don't see how this is approach is an "*anti-pattern*" ...
What env2 allows is: 
+ a *simple*(*er*) way to load any environment variables you have from a **file** while in *development*
+ reference the environment variable using the standard node.js way: `process.env.VAR_NAME`
+ no need to *invoke* a getter method to access environment variables ( ... we were trying to *avoid* `env.getVar('MY_VAR')` everywhere )
+ if the variable has been set in the environment (either by `export`ing it or in a bash script, etc.) variable does *not* get over-written. (i.e. *complies* with **12fa**) 
+ Teams of developers can share the `.env` or `env.json` file in a private way (e.g: Google Docs or Private Repo) 

Our *original* problem was that **iTerm** ***does not remember*** environment variables which we `export` from one session to the next so we kept having to export them by _pasting_ a list of `export` commands.

**Comment by timruffles** [comment]
It's an anti-pattern for people with the problems 12fa solve: it's a great pattern for other people as I said above.

**Comment by nelsonic** [comment]
But we can still use `ansible` or `salt` or `jenkins` or `codeship` to _deploy_ our app while _conforming_ to **12fa** ... env2 works both *locally* (*while developing*) and anywhere we control the steps in the deployment process *but* ***degrades gracefully*** when invoked in production.

**Comment by nelsonic** [comment]
Sorry if I'm being a bit *thick* here... but I want to understand what is wrong with this approach...

**Comment by timruffles** [comment]
As said a few times, I <3 `env2`, I <3 the approach which I use often and will keep using, maybe even via `env2`.

I just can't see the point of quoting a very specific approach to config when `env2` does something completely different.

**Comment by nelsonic** [comment]
Would it be *betterer* if the Readme did not *open* with mentioning 12fa then?

**Comment by timruffles** [comment]
Sure, or even only mention it under "other approaches that might work for you" :)
