### ISSUE TITLE
How does module.parent.id work?

### ISSUE THREAD

**Issue by rjmk** [dwyl/env2#12]
Apparently "[t]ypically this is the fully resolved filename" of the requiring module. But why would there be a 'node_modules' in that path when we require from a module in our project? How is the id property different from the filename property?

**Comment by nelsonic** [comment]
I'm *so* `excite` to read the @rjmk explanation of `module.parent` ! :sparkling_heart:

**Comment by nelsonic** [comment]
@rjmk if you have time to add a description of how `module.parent.id` please re-open this issue and PR into the Readme. thanks!
