### ISSUE TITLE
Why decache?

### ISSUE THREAD

**Issue by rjmk** [dwyl/env2#13]
I don't think that we keep any state within env2 (apart from loading in path and fs; do they keep state?). Why is it necessary to decache the module?

**Comment by nelsonic** [comment]
@FilWisher aksked this *exact* question earlier today: #10 
You are **100% correct**; we don't *need* to `decache` the module ... I just do it out of habit to have a clean test each time.
Feel free to remove any surplus `decache` in your next PR. :+1:
