### ISSUE TITLE
Should we convert the string values coming from .env files to JS primitives?

### ISSUE THREAD

**Issue by efidiles** [dwyl/env2#16]
At the moment things like: `ENV_TEST_VAR=true` read from .env files are string values in process.env.ENV_TEST_VAR.

Converting to primitive types would also make things more consistent with the case of using .json files.

An idea would be to update the `add_dot_env_line_to_json` function to:

```javascript
function add_dot_env_line_to_json (json, env_variable) {  
  var environment_parts = env_variable.split('=');  
  try {  
    json[environment_parts[0]] = JSON.parse(environment_parts[1]);
  }
  catch(e){
    json[environment_parts[0]] = environment_parts[1];
  } 
  return json;
}
```

Let me know if this would suffice or if there's a better solution and I'll create a PR.

**Comment by efidiles** [comment]
sorry.. stupid question. in both cases values are strings. ignore this

**Comment by nelsonic** [comment]
@efidiles are you happy this will do what you need it to? (If not, we're here to help!)
if you end up using it, would you mind :star:-ing it to signal to others  that you find it useful? 
Thanks! :+1:
