### ISSUE TITLE
Why does this beat a .env file?

### ISSUE THREAD

**Issue by rjmk** [dwyl/env2#2]
Is it because it's more node-y / self-contained than a bash-y .env?

**Comment by nelsonic** [comment]
Go on...

**Comment by rjmk** [comment]
Well the main way I've seen of managing environment variables is with a .env file and maybe a porduction.env file. In them, the environment variables are just listed out as

```bash
A_VARIABLE=xyz
...
```

A simple way to run this is with some of the Heroku command line tools (but this is not very self-contained) but the fact that it's _almost_ a sequence of shell commands means it would be simple to write a script to turn it into one. However, I suppose that's not necessary for a node app.

**Comment by nelsonic** [comment]
@rjmk we could *easily* support a `.env` file. 
in fact I *prefer* it to a `.json` file.
Do you have time to write a PR?

**Comment by nelsonic** [comment]
Possible sources of inspiration: 
+ https://github.com/grimen/node-env-file
+ https://github.com/motdotla/dotenv

Differentiator: ours will have **100% test coverage** (*aka reliability*).

**Comment by rjmk** [comment]
Sorted!
