### ISSUE TITLE
Environment variables with '=' won't work in '.env' files

### ISSUE THREAD

**Issue by rjmk** [dwyl/env2#31]
If you are using a `.env` version of the file and have a '=' in the value of the environment variable, you will not get the correct value of the environment variable, because of the fact that only the second segment is used after splitting on '=' (https://github.com/dwyl/env2/blob/9f07c9d28011f92688f23044fab7560331924cfc/lib/env.js#L78).

I will fix this.

**Comment by nelsonic** [comment]
@rjmk indeed... 
thanks for reporting and investigating fix. :+1:

**Comment by rjmk** [comment]
@nelsonic You can also thank me for introducing the bug! :+1:

**Comment by nelsonic** [comment]
This was introduced in response to a *user* request. those pesky users...!
