### ISSUE TITLE
server can't find env2

### ISSUE THREAD

**Issue by RachBLondon** [dwyl/env2#39]
Hi, 

I am running a node express server, and have npm i --save env2 (it's in package.json and node_modules folder) but for some reason my sever keeps returning the error that it can't locate env2.
<img width="947" alt="screen shot 2016-08-07 at 11 40 02" src="https://cloud.githubusercontent.com/assets/8742251/17461953/234417f8-5c94-11e6-843d-74b89b525fe2.png">

Do you know why this might be happening? Thanks!

**Comment by benjaminlees** [comment]
Hi Rachel,

Is this locally ?

have you deleted and reinstalled your node_modules ?

Best,
Benji

**Comment by RachBLondon** [comment]
Hi Benji,

Yeah its local and tried deleting and re installing and still got the same result. I am running node v6.3.1.

Thanks

**Comment by benjaminlees** [comment]
Cool try changing your node version to version 5 and reinstall node-modules.

Just to see if it makes a difference.

**Comment by SimonLab** [comment]
Hi Rachel, Hi Benji

Rachel are you talking about the warning message, "env2 was required to load an .env file"?
env2 is installed because it's this module which display this warning message. You just need to be sure that you have a .env (or config.env) file on the root path of your server. Although the message it's just a warning so you don't need to worry if you don't need to define any environment variables yet.

**Comment by RachBLondon** [comment]
@SimonLab  Yeah I have a .env file in the root directory (tried naming config.env as well). It's odd because in the error message it always seems to want to look for the .env file in the parent of the root directory (even when I move the .env file to that location, the error then looks for it in the grandparent directory).

I was using shrinkwrap but have deleted that and am still getting errors.

@benjaminlees tried switching back to v4.4.0 and still getting the same error :-(

**Comment by RachBLondon** [comment]
@benjaminlees @SimonLab Thanks for you help, Simon you were right, I had an error with the file path in my server. All working now. Cheers!
