### ISSUE TITLE
Color Scheme for Warning Message on Windows

### ISSUE THREAD

**Issue by nelsonic** [dwyl/env2#40]
The word `Warning` is not v. legible on Windows: (_click to open the larger version_)
![env2 warning windows](https://cloud.githubusercontent.com/assets/10284464/18492007/039a1032-79be-11e6-86e0-43d545226c5f.png)
Which makes it "unfriendly" to beginners ... 😞 

originally reported by @cepm-nate on https://github.com/dwyl/learn-nightwatch/issues/29#issuecomment-246830572

> Note: not so much a "bug" ... just not great for readability.

**Comment by cepm-nate** [comment]
Who can't read white on yellow? (black on yellow might be better)

**Comment by nelsonic** [comment]
@cepm-nate yeah, you're right. _really_ need to _fix_ that... _do you have time to help_...?

**Comment by cepm-nate** [comment]
I haven't coded any of env2, but it looks like around line 42 of env.js, they set "bold" to `\u001b[1m`, and put that in front of the word "Warning". Something about that sets the background to yellow on windows, and either leaves the forground white, or sets it to white. Not sure which. This does not corrispond to the windows command shell command of using "COLOR XX" at all, so I'm at a loss as to what the `1m` should actually be.

**Comment by nelsonic** [comment]
Given that no _users_ have complained about this, I'm closing it.
If you are Windows user and have trouble seeing the colors in your terminal,
consider using https://github.com/microsoft/terminal 💡
