### ISSUE TITLE
JSON.parse error causes file not found

### ISSUE THREAD

**Issue by des-des** [dwyl/env2#43]
There is not try / catch around the JSON.parse. So parse errors cause env2 to output a not found error

**Comment by nelsonic** [comment]
@des-des thanks for reporting this! 🥇    (😞 )
If you have time to submit a PR with the `try/catch` we can get it updated ASAP. 👍

**Comment by SimonLab** [comment]
I think this issue has been resolved with #44.
@des-des (:wave: ) can this issue be closed?

**Comment by des-des** [comment]
Ya seems like it! Hope all is good with you - sorry not to have closed!
