### ISSUE TITLE
Shameless plug

### ISSUE THREAD

**Issue by jedwards1211** [dwyl/env2#45]
Hey @nelsonic, check out my [defaultenv](https://github.com/jcoreio/defaultenv) package I've created to solve the same problems -- I think you might like my approach:
* It also allows you to use `.js` files to export default variables, so you can compute values dynamically if need be
* It doesn't touch your app code -- instead it sets environment variables and then runs any command (e.g. `defaultenv env/dev.js env/local.js -- npm start`)

**Comment by nelsonic** [comment]
@jedwards1211 nice one. We are using `.env` file because it's it's easy for us to deploy it to our prod servers (Heroku, AWS, Azure etc.) but the `.js` approach is good for many apps too! 👍

**Comment by nelsonic** [comment]
(Closed as not strictly and issue in `env2` module... 😉 )

**Comment by jedwards1211** [comment]
Yeah fair enough :)  I created `defaultenv` mainly for launching servers in development in dev/prod mode.
